version: '3'
services:
  auth_postgres:
    container_name: auth_postgres
    image: postgres:13
    environment:
      POSTGRES_USER: app_auth
      POSTGRES_PASSWORD: 123qwe_auth
      POSTGRES_DB: auth_database
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    expose:
      - "6379"

volumes:
  auth_pgdata: