version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./.env-dev

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
