version: '3'
services:
  postgres:
    image: postgres:13
    expose:
      - "5432"
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    env_file:
      - auth/.env

  redis:
    image: redis:7.0-alpine
    expose:
      - "6379"
