"""empty message

Revision ID: 442fbb5739db
Revises: 96efd417a09a
Create Date: 2023-02-28 20:14:22.149853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "442fbb5739db"
down_revision = "96efd417a09a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(
            sa.Column("first_name", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("last_name", sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
